server {
    listen 8080;
    server_name _;

    location / {
        proxy_ssl_server_name on;
        proxy_set_header Host jobalart-news.higgsfield.app;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass https://jobalart-news.higgsfield.app;
        proxy_redirect https://jobalart-news.higgsfield.app/ /;
    }
}
